var json = {
	"defaultBuff01": {
		"name"			: ["Buff Name:" , "Heroism"],
		"rounds"		: ["Rounds:" , "300"],
		"type"			: ["Buff Type:" , "Morale"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "2"],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , ""],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , "2"],
		"reflex"		: ["Reflex:" , "2"],
		"will"			: ["Will:" , "2"],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff02": {
		"name"			: ["Buff Name:" , "Conviction"],
		"rounds"		: ["Rounds:" , "5"],
		"type"			: ["Buff Type:" , "Morale"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , "2"],
		"reflex"		: ["Reflex:" , "2"],
		"will"			: ["Will:" , "2"],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff03": {
		"name"			: ["Buff Name:" , "Recitation"],
		"rounds"		: ["Rounds:" , "7"],
		"type"			: ["Buff Type:" , "Untyped"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "2"],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , "2"],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , "2"],
		"reflex"		: ["Reflex:" , "2"],
		"will"			: ["Will:" , "2"],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "4"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff04": {
		"name"			: ["Buff Name:" , "Bull's Strength"],
		"rounds"		: ["Rounds:" , "30"],
		"type"			: ["Buff Type:" , "Enhancement"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , "4"],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff05": {
		"name"			: ["Buff Name:" , "Cat's Grace"],
		"rounds"		: ["Rounds:" , "30"],
		"type"			: ["Buff Type:" , "Enhancement"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , "4"],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff06": {
		"name"			: ["Buff Name:" , "Bear's Endurance"],
		"rounds"		: ["Rounds:" , "30"],
		"type"			: ["Buff Type:" , "Enhancement"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , "4"],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff07": {
		"name"			: ["Buff Name:" , "Fox's Cunning"],
		"rounds"		: ["Rounds:" , "30"],
		"type"			: ["Buff Type:" , "Enhancement"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , "4"],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff08": {
		"name"			: ["Buff Name:" , "Owl's Wisdom"],
		"rounds"		: ["Rounds:" , "30"],
		"type"			: ["Buff Type:" , "Enhancement"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , "4"],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff09": {
		"name"			: ["Buff Name:" , "Eagle's Splendor"],
		"rounds"		: ["Rounds:" , "30"],
		"type"			: ["Buff Type:" , "Enhancement"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , "4"],
		"circle"		: ["Circle:" , "2"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff10": {
		"name"			: ["Buff Name:" , "Righteous Wrath of the Faithful"],
		"rounds"		: ["Rounds:" , "9"],
		"type"			: ["Buff Type:" , "Morale"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "3"],
		"damage"		: ["Damage:" , "3"],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "5"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff11": {
		"name"			: ["Buff Name:" , "Righteous Might"],
		"rounds"		: ["Rounds:" , "9"],
		"type"			: ["Buff Type:" , "Untyped"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , "4"],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , "8"],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , "4"],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "5"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff12": {
		"name"			: ["Buff Name:" , "Divine Power"],
		"rounds"		: ["Rounds:" , "7"],
		"type"			: ["Buff Type:" , "Enhancement"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "2"],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , "6"],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "4"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff13": {
		"name"			: ["Buff Name:" , "Sacred Haven"],
		"rounds"		: ["Rounds:" , "15"],
		"type"			: ["Buff Type:" , "Untyped"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , "2"],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "4"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff14": {
		"name"			: ["Buff Name:" , "Divine Favor"],
		"rounds"		: ["Rounds:" , "10"],
		"type"			: ["Buff Type:" , "Untyped"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "2"],
		"damage"		: ["Damage:" , "2"],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "1"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff15": {
		"name"			: ["Buff Name:" , "Bless"],
		"rounds"		: ["Rounds:" , "10"],
		"type"			: ["Buff Type:" , "Morale"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "1"],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , "1"],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "1"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff16": {
		"name"			: ["Buff Name:" , "Prayer"],
		"rounds"		: ["Rounds:" , "5"],
		"type"			: ["Buff Type:" , "Untyped"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "1"],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , "1"],
		"reflex"		: ["Reflex:" , "1"],
		"will"			: ["Will:" , "1"],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "3"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff17": {
		"name"			: ["Buff Name:" , "Good Hope"],
		"rounds"		: ["Rounds:" , "70"],
		"type"			: ["Buff Type:" , "Morale"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "2"],
		"damage"		: ["Damage:" , "2"],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , "2"],
		"reflex"		: ["Reflex:" , "2"],
		"will"			: ["Will:" , "2"],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "3"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff18": {
		"name"			: ["Buff Name:" , "Shield of Faith"],
		"rounds"		: ["Rounds:" , "10"],
		"type"			: ["Buff Type:" , "Deflection"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , "2"],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "1"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff19": {
		"name"			: ["Buff Name:" , "Greater Heroism"],
		"rounds"		: ["Rounds:" , "110"],
		"type"			: ["Buff Type:" , "Morale"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , "4"],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , ""],
		"touch"			: ["To Touch:" , "Yes"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , "4"],
		"reflex"		: ["Reflex:" , "4"],
		"will"			: ["Will:" , "4"],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "6"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	"defaultBuff20": {
		"name"			: ["Buff Name:" , "Mage Armor"],
		"rounds"		: ["Rounds:" , "600"],
		"type"			: ["Buff Type:" , "Untyped"],//Values: Untyped , Morale, Enhancement , Deflection 
		"tohit"			: ["To Hit:" , ""],
		"damage"		: ["Damage:" , ""],
		"ac"			: ["AC:" , "4"],
		"touch"			: ["To Touch:" , "No"],//Checkbox, Value: Yes , No
		"fortitude"		: ["Fortitude:" , ""],
		"reflex"		: ["Reflex:" , ""],
		"will"			: ["Will:" , ""],
		"strength"		: ["Strength:" , ""],
		"dexterity"		: ["Dexterity:" , ""],
		"constitution"	: ["Constitution:" , ""],
		"intelligence"	: ["Intelligence:" , ""],
		"wisdom"		: ["Wisdom:" , ""],
		"charisma"		: ["Charisma:" , ""],
		"circle"		: ["Circle:" , "1"],//Values: # 1-9
		"buffGame"		: ["Buff Game:" , "DND35"],
		"active"		: ["Active:", "No"],
	},
	
};